/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;
//import com.sun.glass.events.KeyEvent;
import java.util.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;

/**
 *
 * @author Nurul AD
 */
public class Formorder extends javax.swing.JInternalFrame {
   DefaultTableModel tm;
   String[] judul={"Kode Sepatu","Merk Sepatu","Harga","Qty","Subtotal"};
    Date now = new Date();
    SimpleDateFormat tgl = new SimpleDateFormat("dd-MMM-yyyy");

    koneksijual kj = new koneksijual();
    order tb = new order();

    /**
     * Creates new form Formorder
     */
    public Formorder() {
        initComponents();
       TampilGrid();
        Btsimpan.setEnabled(false);
        nonaktif();
    }
    
    void IsiKode(){
        try{
            kj.connect();
            kj.rs=kj.st.executeQuery("select *from t_sepatu");
            while(kj.rs.next()){
                CbKode.addItem(kj.rs.getString("kd_sepatu"));
            }
            kj.rs.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Kesalahan Isi Kode"+e);
        }
    }
    
    void nomor(){
        kj.connect();
        Date a = new Date();
        SimpleDateFormat b = new SimpleDateFormat("ddMMyy-");
        String time = b.format(a);
        try{
            kj.rs=kj.st.executeQuery("select right(no_order,3) as x from tb_order order by no_order desc");
            if(kj.rs.next()){
                int kode = Integer.parseInt(kj.rs.getString("x"))+1;
                Jno.setText(time+"00"+Integer.toString(kode));
            }else{
                int kode = 1;
                Jno.setText(time+"00"+Integer.toString(kode));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Salah Penomoran"+e);
        }
        
    }
    
    void TampilBuku(){      
        try{
            kj.connect();
            kj.rs=kj.st.executeQuery("select *from t_sepatu where kd_sepatu='"+CbKode.getSelectedItem().toString()+"'");
            if(kj.rs.next()){
                Jmerk.setText(kj.rs.getString("nm_sepatu"));
                Jharga.setText(kj.rs.getString("harga"));
            }else{
                Jmerk.setText("");
                Jharga.setText("");
            }
            kj.rs.close();
            kj.con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Kesalahan Tampil Buku"+e);
        }
    }
    
   void TampilGrid(){
       tm = new DefaultTableModel(null,judul);
       try{
            kj.connect();
            kj.rs=kj.st.executeQuery("select *from Sementara");
            while(kj.rs.next()){
                String a = kj.rs.getString("kd_sepatu");
                String b = kj.rs.getString("nm_sepatu");
                String c = kj.rs.getString("harga");
                String d = kj.rs.getString("qty");
                String e = kj.rs.getString("subtotal");
                
                String[] data ={a,b,c,d,e};
                tm.addRow(data);
           }
            tb_sepatu.setModel(tm);
        }catch(SQLException e){
          JOptionPane.showMessageDialog(null, "Tabel Belum Tampil"+e);
        }
    }
    
    void bersih(){
        Jno.setText("");
        CbKode.setSelectedItem("PILIH");
        Jmerk.setText("");
        Jqty.setText("");
        Jharga.setText("");
        Jsub.setText("");
        Jkem.setText("");
        Jubay.setText("");
        Jtotbay.setText("");
    }
    
    void aktif(){
        CbKode.setEnabled(true);
        Jqty.setEnabled(true);
        Jubay.setEnabled(true);
    }
    
    void nonaktif(){
        Jno.setEnabled(false);
        Jtgl.setEnabled(false);
        CbKode.setEnabled(false);
        Jmerk.setEnabled(false);
        Jqty.setEnabled(false);
        Jharga.setEnabled(false);
        Jsub.setEnabled(false);
        Jkem.setEnabled(false);
        Jubay.setEnabled(false);
        Jtotbay.setEnabled(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        Jno = new javax.swing.JTextField();
        Jtgl = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        s = new javax.swing.JPanel();
        CbKode = new javax.swing.JComboBox<>();
        Jmerk = new javax.swing.JTextField();
        Jharga = new javax.swing.JTextField();
        Jqty = new javax.swing.JTextField();
        Jsub = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sepatu = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Jtotbay = new javax.swing.JTextField();
        Jubay = new javax.swing.JTextField();
        Jkem = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Btbatal = new javax.swing.JButton();
        Bttambah = new javax.swing.JButton();
        Btsimpan = new javax.swing.JButton();
        Btkeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Transaksi"));
        jPanel1.setLayout(null);

        Jno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JnoActionPerformed(evt);
            }
        });
        jPanel1.add(Jno);
        Jno.setBounds(220, 40, 190, 30);
        jPanel1.add(Jtgl);
        Jtgl.setBounds(220, 90, 190, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order-1.jpg"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 20, 410, 120);

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(12, 12, 430, 150);

        s.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Transaksi"));
        s.setLayout(null);

        CbKode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbKodeActionPerformed(evt);
            }
        });
        s.add(CbKode);
        CbKode.setBounds(60, 80, 120, 40);
        s.add(Jmerk);
        Jmerk.setBounds(230, 80, 148, 40);
        s.add(Jharga);
        Jharga.setBounds(450, 80, 160, 40);

        Jqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JqtyKeyPressed(evt);
            }
        });
        s.add(Jqty);
        Jqty.setBounds(660, 80, 130, 40);
        s.add(Jsub);
        Jsub.setBounds(840, 80, 130, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order-2.jpg"))); // NOI18N
        s.add(jLabel12);
        jLabel12.setBounds(10, 20, 990, 120);

        jDesktopPane1.add(s);
        s.setBounds(10, 170, 1010, 150);

        tb_sepatu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_sepatu);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 330, 1016, 104);

        jLabel8.setText("Total Bayar");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(60, 450, 55, 15);

        jLabel9.setText("Uang Bayar");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(330, 450, 57, 15);

        jLabel10.setText("Uang Kembali");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(630, 450, 65, 15);
        jDesktopPane1.add(Jtotbay);
        Jtotbay.setBounds(130, 450, 137, 30);

        Jubay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JubayActionPerformed(evt);
            }
        });
        Jubay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JubayKeyPressed(evt);
            }
        });
        jDesktopPane1.add(Jubay);
        Jubay.setBounds(400, 450, 137, 30);

        Jkem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JkemActionPerformed(evt);
            }
        });
        jDesktopPane1.add(Jkem);
        Jkem.setBounds(710, 450, 137, 30);

        jPanel2.setLayout(null);

        Btbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Batal.png"))); // NOI18N
        Btbatal.setText("Batal");
        Btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtbatalActionPerformed(evt);
            }
        });
        jPanel2.add(Btbatal);
        Btbatal.setBounds(300, 40, 112, 50);

        Bttambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tambah.png"))); // NOI18N
        Bttambah.setText("Tambah");
        Bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttambahActionPerformed(evt);
            }
        });
        jPanel2.add(Bttambah);
        Bttambah.setBounds(20, 40, 130, 50);

        Btsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/simpan.jpg"))); // NOI18N
        Btsimpan.setText("Simpan");
        Btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtsimpanActionPerformed(evt);
            }
        });
        jPanel2.add(Btsimpan);
        Btsimpan.setBounds(160, 40, 120, 50);

        Btkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log_out-512.png"))); // NOI18N
        Btkeluar.setText("Keluar");
        Btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(Btkeluar);
        Btkeluar.setBounds(420, 40, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order-3.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(4, 0, 560, 150);

        jDesktopPane1.add(jPanel2);
        jPanel2.setBounds(448, 12, 570, 150);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(1, 0, 1040, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JnoActionPerformed

    private void JkemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JkemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JkemActionPerformed

    private void BttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttambahActionPerformed
        // TODO add your handling code here:
        nomor();
        Jtgl.setText(tgl.format(now));
        IsiKode();
        aktif();
        
        Btsimpan.setEnabled(true);
        Bttambah.setEnabled(false);
    }//GEN-LAST:event_BttambahActionPerformed

    private void CbKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbKodeActionPerformed
        // TODO add your handling code here:
         TampilBuku();
        Jqty.grabFocus();
    }//GEN-LAST:event_CbKodeActionPerformed

    private void BtsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtsimpanActionPerformed
        // TODO add your handling code here:
        tb.setNota(Jno.getText());
        tb.setTgl(Jtgl.getText());
        tb.setKode(CbKode.getSelectedItem().toString());
        tb.setMerk(Jmerk.getText());
        tb.setHarga(Long.parseLong(Jharga.getText()));
        tb.Simpantb_order();
        tb.HapusGrid();
        TampilGrid();
        bersih();
        nonaktif();
        Bttambah.setEnabled(true);
        Btsimpan.setEnabled(false);
    }//GEN-LAST:event_BtsimpanActionPerformed

    private void BtkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtkeluarActionPerformed
        // TODO add your handling code here:
        int x;
        x = JOptionPane.showConfirmDialog(null, "Anda yakin ingin keluar?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION)
            dispose();
        else
            return;
    }//GEN-LAST:event_BtkeluarActionPerformed

    private void JqtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JqtyKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            tb.setQty(Long.parseLong(Jqty.getText()));
            tb.setHarga(Long.parseLong(Jharga.getText()));
            tb.setNota(Jno.getText());
            tb.setKode(CbKode.getSelectedItem().toString());
            tb.setMerk(Jmerk.getText());
            Jsub.setText(Long.toString(tb.getSubtotal()));
            Jtotbay.setText(Long.toString(tb.getTotal()));
            
            tb.SimpanSementara();
            tb.SimpanDetail();
            TampilGrid();
            tb.KurangStok();
            Jqty.setText(title);
        }
    }//GEN-LAST:event_JqtyKeyPressed

    private void JubayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JubayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JubayActionPerformed

    private void JubayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JubayKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tb.setTotal(Long.parseLong(Jtotbay.getText()));
            tb.setUbay(Long.parseLong(Jubay.getText()));
            Jkem.setText(Long.toString(tb.getUkem()));
        }
    }//GEN-LAST:event_JubayKeyPressed

    private void BtbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtbatalActionPerformed
        // TODO add your handling code here:
         bersih();
        nonaktif();
    }//GEN-LAST:event_BtbatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btbatal;
    private javax.swing.JButton Btkeluar;
    private javax.swing.JButton Btsimpan;
    private javax.swing.JButton Bttambah;
    private javax.swing.JComboBox<String> CbKode;
    private javax.swing.JTextField Jharga;
    private javax.swing.JTextField Jkem;
    private javax.swing.JTextField Jmerk;
    private javax.swing.JTextField Jno;
    private javax.swing.JTextField Jqty;
    private javax.swing.JTextField Jsub;
    private javax.swing.JTextField Jtgl;
    private javax.swing.JTextField Jtotbay;
    private javax.swing.JTextField Jubay;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel s;
    private javax.swing.JTable tb_sepatu;
    // End of variables declaration//GEN-END:variables
}
