/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import javax.swing.JOptionPane;

/**
 *
 * @author Nurul AD
 */
public class Formuser extends javax.swing.JInternalFrame {
    
    koneksijual kj = new koneksijual();
     

    /**
     * Creates new form Flogin
     */
    public Formuser() {
        initComponents();
    }
    void bersih()
    {
      Juser.setText("");
      Jpass.setText("");
                    
    }
     
    
   void TampilMenu()
    {
       kj.connect();
       try
        {
            kj.st=kj.con.createStatement();
            kj.rs = kj.st.executeQuery("select * from user where nm_user='"+Juser.getText().trim()+"' and password='"+Jpass.getText().trim()+"'");
            if(kj.rs.next())
            {
                String nama=kj.rs.getString("nm_user");
                JOptionPane.showMessageDialog(this, "Selamat Datang "+nama+"","Welcome", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                Fmenuuser menu= new Fmenuuser();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "user tidak ditemukan","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(this, "gagal"+e);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        Jpass = new javax.swing.JPasswordField();
        user = new javax.swing.JButton();
        Juser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Form User");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        jPanel1.add(Jpass);
        Jpass.setBounds(660, 210, 220, 40);

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user);
        user.setBounds(670, 310, 100, 80);

        Juser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuserActionPerformed(evt);
            }
        });
        jPanel1.add(Juser);
        Juser.setBounds(660, 100, 220, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1030, 500);

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 510);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 1030, 629);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        TampilMenu();
    }//GEN-LAST:event_userActionPerformed

    private void JuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JuserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Jpass;
    private javax.swing.JTextField Juser;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton user;
    // End of variables declaration//GEN-END:variables
}
