/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Nurul AD
 */
public class Formregispetugas extends javax.swing.JInternalFrame {
    DefaultTableModel tm;
    String[] spt={"kd_petugas", "nm_petugas", "jenkel", "umur_petugas", "alamat_petugas"};

koneksijual kj =new koneksijual();
regispetugas Regis = new regispetugas(); 
    /**
     * Creates new form Formregispetugas
     */
    public Formregispetugas() {
        initComponents();
        
        nonaktif();
        tampil();
        Btbatal.setEnabled(false);
        Btubah.setEnabled(false);
        Bthapus.setEnabled(false);
        Btupdate.setEnabled(false);
        Btsimpan.setEnabled(false);        
    }
    
    void tampil()
{
    tm=new DefaultTableModel(null,spt);
    try
    {
        kj.connect();
        kj.rs=kj.st.executeQuery("select * from petugas");
        while (kj.rs.next())
        {
            String a=kj.rs.getString("kd_petugas");
            String b=kj.rs.getString("nm_petugas");
            String c=kj.rs.getString("jenkel");
            String d=kj.rs.getString("umur_petugas");
            String e=kj.rs.getString("alamat_petugas");
           // String f=kj.rs.getString("password");
            //String g=kj.rs.getString("stok");
            
            String[] data={a,b,c,d,e};
            tm.addRow(data);
            
        }
        tb_petugas.setModel(tm);
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(null, "Tabel belum muncul" +e);
    }
}
    
    void nonaktif(){
        kdpetugas.setEnabled(false);
        nmpetugas.setEnabled(false);
        laki.setEnabled(false);
        perempuan.setEnabled(false);
        umur.setEnabled(false);
        alamat.setEnabled(false);
        pass.setEnabled(false);
    }
    
    void aktif(){
        kdpetugas.setEnabled(true);
        nmpetugas.setEnabled(true);
        laki.setEnabled(true);
        perempuan.setEnabled(true);
        umur.setEnabled(true);
        alamat.setEnabled(true);
        pass.setEnabled(true);
    }
    
    void bersih(){
    kdpetugas.setText("");
    nmpetugas.setText("");
    bg.clearSelection();
    umur.setText("");
    alamat.setText("");
    pass.setText("");
   
       
       
    }
    

    
         void no_auto()
    {
        try
        {
            int kode;
            kj.rs=kj.st.executeQuery("select right(kd_petugas,3) as x from petugas order by kd_petugas desc");
            if (kj.rs.next())
            {
                kode = Integer.parseInt(kj.rs.getString("x"))+1;
                kdpetugas.setText("PTG00"+Integer.toString(kode));
            }
            else
            {
                kode=1;
                kdpetugas.setText("PTG00"+Integer.toString(kode));
                
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Kode tidak bisa tampil"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        kdpetugas = new javax.swing.JTextField();
        nmpetugas = new javax.swing.JTextField();
        umur = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        pass = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Bttambah = new javax.swing.JButton();
        Btsimpan = new javax.swing.JButton();
        Btbatal = new javax.swing.JButton();
        Btubah = new javax.swing.JButton();
        Btupdate = new javax.swing.JButton();
        Bthapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_petugas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)), "Input Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel1.setLayout(null);
        jPanel1.add(kdpetugas);
        kdpetugas.setBounds(200, 50, 170, 30);
        jPanel1.add(nmpetugas);
        nmpetugas.setBounds(200, 100, 170, 30);

        umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umurActionPerformed(evt);
            }
        });
        jPanel1.add(umur);
        umur.setBounds(200, 200, 176, 30);
        jPanel1.add(alamat);
        alamat.setBounds(200, 250, 176, 30);

        laki.setText("Laki-laki");
        jPanel1.add(laki);
        laki.setBounds(200, 150, 100, 30);

        perempuan.setText("Perempuan");
        jPanel1.add(perempuan);
        perempuan.setBounds(310, 150, 110, 30);

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass);
        pass.setBounds(200, 299, 176, 30);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 20, 0, 330);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regis-petugas.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 490, 340);

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(10, 10, 510, 360);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)), "Tools", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel2.setLayout(null);

        Bttambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tambah.png"))); // NOI18N
        Bttambah.setText("Tambah");
        Bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttambahActionPerformed(evt);
            }
        });
        jPanel2.add(Bttambah);
        Bttambah.setBounds(30, 50, 130, 50);

        Btsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/simpan.jpg"))); // NOI18N
        Btsimpan.setText("Simpan");
        Btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtsimpanActionPerformed(evt);
            }
        });
        jPanel2.add(Btsimpan);
        Btsimpan.setBounds(180, 50, 120, 50);

        Btbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Batal.png"))); // NOI18N
        Btbatal.setText("Batal");
        Btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtbatalActionPerformed(evt);
            }
        });
        jPanel2.add(Btbatal);
        Btbatal.setBounds(180, 170, 120, 50);

        Btubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        Btubah.setText("Edit");
        Btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtubahActionPerformed(evt);
            }
        });
        jPanel2.add(Btubah);
        Btubah.setBounds(30, 110, 130, 50);

        Btupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update.png"))); // NOI18N
        Btupdate.setText("Update");
        Btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtupdateActionPerformed(evt);
            }
        });
        jPanel2.add(Btupdate);
        Btupdate.setBounds(180, 110, 120, 50);

        Bthapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hapus.png"))); // NOI18N
        Bthapus.setText("Hapus");
        Bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthapusActionPerformed(evt);
            }
        });
        jPanel2.add(Bthapus);
        Bthapus.setBounds(30, 170, 130, 50);

        jLabel1.setText("Cari Data");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 260, 44, 15);
        jPanel2.add(cari);
        cari.setBounds(30, 290, 167, 19);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cari.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(210, 280, 60, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tools-petugas.jpg"))); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 20, 430, 330);

        jDesktopPane1.add(jPanel2);
        jPanel2.setBounds(559, 10, 450, 360);

        tb_petugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_petugas);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 380, 1000, 126);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(5, 0, 1040, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umurActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void BttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttambahActionPerformed
        // TODO add your handling code here:
        aktif();
        no_auto();
        Btbatal.setEnabled(true);
        Btsimpan.setEnabled(true);
        Bttambah.setEnabled(false);
        Btubah.setEnabled(false);
        kdpetugas.grabFocus();
    }//GEN-LAST:event_BttambahActionPerformed

    private void BtsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtsimpanActionPerformed
        // TODO add your handling code here:
        //regis.setKode(tkduser.getText());
        Regis.setKode(kdpetugas.getText());
        Regis.setNama(nmpetugas.getText());
        if(laki.isSelected())
        Regis.setKel(laki.getText());
        else
        Regis.setKel(perempuan.getText());
        Regis.setUmr(Long.parseLong(umur.getText()));
        Regis.setAlmt(alamat.getText());
        Regis.setPss(pass.getText());
        Regis.simpan();
        bersih();
        nonaktif();

    }//GEN-LAST:event_BtsimpanActionPerformed

    private void BtbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtbatalActionPerformed
        // TODO add your handling code here:
        bersih();
        nonaktif();
        Bttambah.setEnabled(true);
        Btsimpan.setEnabled(false);
        Btbatal.setEnabled(false);
        Btupdate.setEnabled(false);
        Bthapus.setEnabled(false);
        Btubah.setEnabled(false);
    }//GEN-LAST:event_BtbatalActionPerformed

    private void BtubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtubahActionPerformed
        // TODO add your handling code here:
        aktif();
        Bttambah.setEnabled(false);
        Btsimpan.setEnabled(false);
        Btubah.setEnabled(false);
        Btupdate.setEnabled(true);
        Bthapus.setEnabled(true);
        Btbatal.setEnabled(true);
        kdpetugas.setEnabled(false);
    }//GEN-LAST:event_BtubahActionPerformed

    private void BtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtupdateActionPerformed
        // TODO add your handling code here:
        aktif();Regis.getKode();
        Regis.setNama(nmpetugas.getText());
        if(laki.isSelected())
        Regis.setKel(laki.getText());
        else
        Regis.setKel(perempuan.getText());
        Regis.setUmr(Long.parseLong(umur.getText()));
        Regis.setAlmt(alamat.getText());
        Regis.setPss(pass.getText());
        kdpetugas.setEnabled(false);

    }//GEN-LAST:event_BtupdateActionPerformed

    private void BthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthapusActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Ingin dihapus ? ","Konfirmasi ",JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION){
            Regis.hapus();
            bersih();

        }else
        return;
    }//GEN-LAST:event_BthapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Regis.setKode(cari.getText());
        Regis.cari();

        kdpetugas.setText(Regis.getKode());
        nmpetugas.setText(Regis.getNama());
        //   Jenissepatu.setText(Regis.getJenis());
        //   ukuran.setText(Long.toString(Regis.uk));
        if (Regis.getKel().equalsIgnoreCase("dewasa"))
        laki.setSelected(true);
        else
        perempuan.setSelected(true);
        umur.setText(Long.toString(Regis.getUmr()));
        alamat.setText(Regis.getAlmt());
        pass.setText(Regis.getPss());

        Btupdate.setEnabled(true);
        Btubah.setEnabled(true);
        Btbatal.setEnabled(true);
        Bthapus.setEnabled(true);
        Bttambah.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btbatal;
    private javax.swing.JButton Bthapus;
    private javax.swing.JButton Btsimpan;
    private javax.swing.JButton Bttambah;
    private javax.swing.JButton Btubah;
    private javax.swing.JButton Btupdate;
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JTextField cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kdpetugas;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nmpetugas;
    private javax.swing.JPasswordField pass;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JTable tb_petugas;
    private javax.swing.JTextField umur;
    // End of variables declaration//GEN-END:variables
}
