/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author Nurul AD
 */
import javax.swing.table.DefaultTableModel;

public class Formcarisepatu extends javax.swing.JInternalFrame {
     private DefaultTableModel model;
     sepatu Sepatu = new sepatu(); 
    koneksijual kj =new koneksijual();
    
    /**
     * Creates new form carisepatu
     */
    public Formcarisepatu() {
        initComponents();
    
     
              model = new DefaultTableModel ( );
             tb_sepatu.setModel(model);
             model.addColumn("Kode Sepatu");
             model.addColumn("nama Sepatu");
             model.addColumn("Jenis Sepatu");
             model.addColumn("Ukuran Sepatu");
             model.addColumn("Tipe Sepatu");
             model.addColumn("Stock Tersedia");
             
            //  getData(); 
}
    
    //public void getData( ){
     //menghapus isi table tblGaji
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sepatu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jDesktopPane1.setForeground(new java.awt.Color(71, 71, 75));

        tb_sepatu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_sepatu);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(346, 21, 682, 92);

        jPanel2.setLayout(null);
        jPanel2.add(txtCari);
        txtCari.setBounds(63, 93, 170, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cari.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(120, 160, 84, 49);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cari-sepatu.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 320, 300);

        jDesktopPane1.add(jPanel2);
        jPanel2.setBounds(12, 12, 320, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         model.getDataVector( ).removeAllElements( );
     model.fireTableDataChanged( );

     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
         
           kj.connect();
        kj.rs=kj.st.executeQuery("select * from t_sepatu where kd_sepatu like'%" +txtCari.getText()+"%'"+"or nm_sepatu like'%"+txtCari.getText()+"%'");
        while (kj.rs.next())
        {
                Object[ ] obj = new Object[7];
                obj[0] = kj.rs.getString("kd_sepatu");
                obj[1] = kj.rs.getString("Nm_sepatu");
                obj[2] = kj.rs.getString("jenis_sepatu");
                obj[3] = kj.rs.getString("ukuran");
                obj[4] = kj.rs.getString("tipe");
                obj[5] = kj.rs.getString("harga");
                obj[6] = kj.rs.getString("stok");

                model.addRow(obj);
            }
      }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage() );
      }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_sepatu;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
