/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Nurul AD
 */
public class Formadmin extends javax.swing.JInternalFrame {
    
koneksijual kj = new koneksijual();

    /**
     * Creates new form Fadmin
     */
    public Formadmin() {
        initComponents();

    }
    void bersih()
    {
      admin.setText("");
      pass.setText("");      
    }
    
    void TampilMenu()
    {
       kj.connect();
       try
        {
            kj.st=kj.con.createStatement();
            kj.rs = kj.st.executeQuery("select * from petugas where nm_petugas='"+admin.getText().trim()+"' and password='"+pass.getText().trim()+"'");
            if(kj.rs.next())
            {
                String nama=kj.rs.getString("nm_petugas");
                JOptionPane.showMessageDialog(this, "Selamat Datang "+nama+"","Welcome", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                Fmenuadmin menu= new Fmenuadmin();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "user tidak ditemukan","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
       catch (Exception e)
       {
           JOptionPane.showMessageDialog(this, "gagal"+e);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        admin = new javax.swing.JTextField();
        blogin = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Form Admin");
        getContentPane().setLayout(null);

        jDesktopPane2.add(admin);
        admin.setBounds(650, 110, 220, 40);

        blogin.setText("Login");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        jDesktopPane2.add(blogin);
        blogin.setBounds(660, 290, 100, 50);
        jDesktopPane2.add(pass);
        pass.setBounds(650, 210, 220, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.jpg"))); // NOI18N
        jDesktopPane2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1030, 510);

        getContentPane().add(jDesktopPane2);
        jDesktopPane2.setBounds(0, 2, 1030, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        //TODO add your handling code here:
       TampilMenu();
    }//GEN-LAST:event_bloginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admin;
    private javax.swing.JButton blogin;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
