/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Nurul AD
 */
public class Formregisuser extends javax.swing.JInternalFrame {

    DefaultTableModel tm;
    String[] spt={"kd_user", "nm_user", "jenkel", "umur_user", "alamat_user"};
    regis Regis = new regis(); 
    koneksijual kj =new koneksijual();

    /**
     * Creates new form registrasi
     */
    public Formregisuser() {
        initComponents();
        
        nonaktif();
        tampil();
        Btbatal.setEnabled(false);
        Btubah.setEnabled(false);
        Bthapus.setEnabled(false);
        Btupdate.setEnabled(false);
        Btsimpan.setEnabled(false);        
    }
    
    void nonaktif(){
        kduser.setEnabled(false);
        nmuser.setEnabled(false);
        laki.setEnabled(false);
        perempuan.setEnabled(false);
        umur.setEnabled(false);
        alamat.setEnabled(false);
        pass.setEnabled(false);
    }
    
    void aktif(){
        kduser.setEnabled(true);
        nmuser.setEnabled(true);
        laki.setEnabled(true);
        perempuan.setEnabled(true);
        umur.setEnabled(true);
        alamat.setEnabled(true);
        pass.setEnabled(true);
    }
    
    void bersih(){
    kduser.setText("");
    nmuser.setText("");
    bg.clearSelection();
    umur.setText("");
    alamat.setText("");
    pass.setText("");
       
    }
    
    
          void no_auto()
    {
        try
        {
            int kode;
            kj.rs=kj.st.executeQuery("select right(kd_user,3) as x from user order by kd_user desc");
            if (kj.rs.next())
            {
                kode = Integer.parseInt(kj.rs.getString("x"))+1;
                kduser.setText("USR00"+Integer.toString(kode));
            }
            else
            {
                kode=1;
                kduser.setText("USR00"+Integer.toString(kode));
                
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Kode tidak bisa tampil"+e);
        }
    }

    void tampil()
{
    tm=new DefaultTableModel(null,spt);
    try
    {
        kj.connect();
        kj.rs=kj.st.executeQuery("select * from user");
        while (kj.rs.next())
        {
            String a=kj.rs.getString("kd_user");
            String b=kj.rs.getString("nm_user");
            String c=kj.rs.getString("jenkel");
            String d=kj.rs.getString("umur_user");
            String e=kj.rs.getString("alamat_user");
         //   String f=kj.rs.getString("password");
            //String g=kj.rs.getString("stok");
            
            String[] data={a,b,c,d,e};
            tm.addRow(data);
            
        }
        tb_user.setModel(tm);
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(null, "Tabel belum muncul" +e);
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        Bttambah = new javax.swing.JButton();
        Btsimpan = new javax.swing.JButton();
        Btbatal = new javax.swing.JButton();
        Btubah = new javax.swing.JButton();
        Btupdate = new javax.swing.JButton();
        Bthapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_user = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        kduser = new javax.swing.JTextField();
        nmuser = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        umur = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jDesktopPane1.setForeground(new java.awt.Color(71, 71, 75));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)), "Tools", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel2.setLayout(null);

        Bttambah.setText("Tambah");
        Bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttambahActionPerformed(evt);
            }
        });
        jPanel2.add(Bttambah);
        Bttambah.setBounds(30, 40, 150, 50);

        Btsimpan.setText("Simpan");
        Btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtsimpanActionPerformed(evt);
            }
        });
        jPanel2.add(Btsimpan);
        Btsimpan.setBounds(200, 40, 140, 50);

        Btbatal.setText("Batal");
        Btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtbatalActionPerformed(evt);
            }
        });
        jPanel2.add(Btbatal);
        Btbatal.setBounds(200, 160, 140, 50);

        Btubah.setText("Edit");
        Btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtubahActionPerformed(evt);
            }
        });
        jPanel2.add(Btubah);
        Btubah.setBounds(30, 100, 150, 50);

        Btupdate.setText("Update");
        Btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtupdateActionPerformed(evt);
            }
        });
        jPanel2.add(Btupdate);
        Btupdate.setBounds(200, 100, 140, 50);

        Bthapus.setText("Hapus");
        Bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BthapusActionPerformed(evt);
            }
        });
        jPanel2.add(Bthapus);
        Bthapus.setBounds(30, 160, 150, 50);

        jLabel1.setText("Cari Data");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(39, 191, 44, 15);
        jPanel2.add(cari);
        cari.setBounds(30, 240, 180, 40);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(230, 240, 34, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tools-.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 20, 360, 300);

        jDesktopPane1.add(jPanel2);
        jPanel2.setBounds(590, 10, 370, 330);

        tb_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_user);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 350, 1000, 145);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)), "Input Data User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel3.setLayout(null);
        jPanel3.add(kduser);
        kduser.setBounds(160, 50, 161, 30);
        jPanel3.add(nmuser);
        nmuser.setBounds(160, 90, 161, 30);

        bg.add(laki);
        laki.setText("Laki-laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });
        jPanel3.add(laki);
        laki.setBounds(160, 130, 90, 40);

        bg.add(perempuan);
        perempuan.setText("Perempuan");
        jPanel3.add(perempuan);
        perempuan.setBounds(260, 130, 110, 40);

        umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umurActionPerformed(evt);
            }
        });
        jPanel3.add(umur);
        umur.setBounds(160, 180, 160, 30);
        jPanel3.add(alamat);
        alamat.setBounds(160, 219, 160, 30);

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel3.add(pass);
        pass.setBounds(160, 259, 160, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regis-user.jpg"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 20, 450, 300);

        jDesktopPane1.add(jPanel3);
        jPanel3.setBounds(10, 10, 470, 330);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(-1, 12, 1030, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttambahActionPerformed
        // TODO add your handling code here:
        no_auto();
        aktif();
        tampil();
        Btbatal.setEnabled(true);
        Btsimpan.setEnabled(true);
        Bttambah.setEnabled(false);
        Btubah.setEnabled(false);
        kduser.grabFocus();
    }//GEN-LAST:event_BttambahActionPerformed

    private void BtbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtbatalActionPerformed
        // TODO add your handling code here:
        bersih();
        nonaktif();
        Bttambah.setEnabled(true);
        Btsimpan.setEnabled(false);
        Btbatal.setEnabled(false);
        Btupdate.setEnabled(false);
        Bthapus.setEnabled(false);
        Btubah.setEnabled(false);
    }//GEN-LAST:event_BtbatalActionPerformed

    private void BtubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtubahActionPerformed
        // TODO add your handling code here:
        aktif();
        Bttambah.setEnabled(false);
        Btsimpan.setEnabled(false);
        Btubah.setEnabled(false);
        Btupdate.setEnabled(true);
        Bthapus.setEnabled(true);
        Btbatal.setEnabled(true);
        kduser.setEnabled(false);
    }//GEN-LAST:event_BtubahActionPerformed

    private void BtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtupdateActionPerformed
        // TODO add your handling code here:
        aktif();
        Regis.getKode();
        Regis.setNama(nmuser.getText());
        if(laki.isSelected())
           Regis.setKel(laki.getText());
       else
           Regis.setKel(perempuan.getText());
        Regis.setUmr(Long.parseLong(umur.getText()));
        Regis.setAlmt(alamat.getText());
        Regis.setPss(pass.getText());
        kduser.setEnabled(false);
        Regis.update();
        tampil();
        bersih();
        nonaktif();
    }//GEN-LAST:event_BtupdateActionPerformed

    private void BthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BthapusActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Ingin dihapus ? ","Konfirmasi ",JOptionPane.YES_NO_OPTION);
            if(a==JOptionPane.YES_OPTION){
                Regis.hapus();
                bersih();
                
            }else
                return;
    }//GEN-LAST:event_BthapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Regis.setKode(cari.getText());
        Regis.cari();
        
        kduser.setText(Regis.getKode());
        nmuser.setText(Regis.getNama());
     //   Jenissepatu.setText(Regis.getJenis());
     //   ukuran.setText(Long.toString(Regis.uk));
        if (Regis.getKel().equalsIgnoreCase("dewasa"))
                laki.setSelected(true);
            else
                perempuan.setSelected(true);
        umur.setText(Long.toString(Regis.getUmr()));
        alamat.setText(Regis.getAlmt());
        pass.setText(Regis.getPss());
        
        Btupdate.setEnabled(true);
        Btubah.setEnabled(true);
        Btbatal.setEnabled(true);
        Bthapus.setEnabled(true);
        Bttambah.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
        // Regis.sesetJenis(laki.getText());
    }//GEN-LAST:event_lakiActionPerformed

    private void umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umurActionPerformed

    private void BtsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtsimpanActionPerformed
        // TODO add your handling code here:
        //regis.setKode(tkduser.getText());
        Regis.setKode(kduser.getText());
        Regis.setNama(nmuser.getText());
        if(laki.isSelected())
        Regis.setKel(laki.getText());
        else
        Regis.setKel(perempuan.getText());
        Regis.setUmr(Long.parseLong(umur.getText()));
        Regis.setAlmt(alamat.getText());
        Regis.setPss(pass.getText());
        Regis.simpan();
        bersih();
        nonaktif();

    }//GEN-LAST:event_BtsimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btbatal;
    private javax.swing.JButton Bthapus;
    private javax.swing.JButton Btsimpan;
    private javax.swing.JButton Bttambah;
    private javax.swing.JButton Btubah;
    private javax.swing.JButton Btupdate;
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JTextField cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kduser;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nmuser;
    private javax.swing.JPasswordField pass;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JTable tb_user;
    private javax.swing.JTextField umur;
    // End of variables declaration//GEN-END:variables
}
